[package]
name = "zippy-midend"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zippy-common = { path = "../zippy-common" }

im = "15.1"

log = "0.4"
