[package]
name = "corollary"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bimap = "0.6"
pretty = "0.11"
logos = "0.12"

codespan-reporting = "0.11"
env_logger = "0.9"
log = "0.4"
