[workspace]
members = ["crates/*"]

[package]
name = "zippyc"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "zc"
path = "src/main.rs"

[dependencies]
zippy-frontend = { path = "crates/zippy-frontend" }

log = "0.4"
simple_logger = "4.0"
