[package]
name = "corollary"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bimap = "0.6"
im = "15.1"
logos = "0.12"
object = { version = "0.29", features = ["write_std"] }
pretty = "0.11"
ranges = "0.3"

anyhow = "1.0"
codespan-reporting = "0.11"
console = "0.15"
env_logger = "0.9"
log = "0.4"
